global:
  scrape_interval: 15s

scrape_configs:
  - job_name: shorturl
    metrics_path: /api/metrics
    static_configs:
      - targets: ["shorturl:4000"]
  - job_name: qrgen
    static_configs:
      - targets: ["qrgen:5000"]